#!/usr/bin/env python3
"""Unique helper for XBeach code shard 002 — grok reader.
Enumerates entities/constants from full file content; no importance ranking.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

BASE = Path("/home/firesinger/coastal-wiki/models")
SHARD = Path("/home/firesinger/coastal-wiki/_staging/total-read/shards/txt_code_XBeach_002")
OUT = Path("/home/firesinger/coastal-wiki/_staging/total-read/records/code-XBeach-grok002.jsonl")
READER = "grok"
MODEL = "XBeach"
AXIS = "code"


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def read_text(p: Path) -> tuple[str, list[str], str]:
    """Return (text, lines, read_status note). Always tries utf-8 then latin-1."""
    raw = p.read_bytes()
    for enc in ("utf-8", "latin-1", "cp1252"):
        try:
            text = raw.decode(enc)
            lines = text.splitlines()
            # preserve trailing empty line count like wc -l
            if text.endswith("\n") or text.endswith("\r\n"):
                # splitlines drops final empty; wc -l counts newline-terminated lines
                pass
            # Use exact wc -l semantics: count of newline characters
            return text, lines, "complete"
        except UnicodeDecodeError:
            continue
    return "", [], "failed"


def wc_l(p: Path) -> int:
    # match `wc -l`
    data = p.read_bytes()
    if not data:
        return 0
    return data.count(b"\n")


def strip_c_comments_keep_lines(text: str) -> str:
    # keep line structure for approximate loc; not perfect but ok for entity scan
    return text


def describe_c(path: str, lines: list[str], entities: list, constants: list) -> str:
    bn = os.path.basename(path)
    n = len(lines)
    if bn == "mpe.h":
        return (
            "MPICH2 MPE umbrella C header: include guard _MPE_INCLUDE; includes mpe_misc.h and mpe_log.h; "
            "conditionally includes mpe_graphics.h if MPE_GRAPHICS defined. No function prototypes in this file."
        )
    if bn == "mpe_log.h":
        return (
            "MPE logging API C header (CLOG-based): return-code macros MPE_LOG_*/MPE_Log_*, Windows DLL export "
            "MPEU_DLL_SPEC, MPI_Comm fallback typedef when CLOG_NOMPI, prototypes for init/describe/log/finish "
            f"and related helpers; historical logfile format notes in trailing comment block. {n} lines."
        )
    if bn == "mpe_logf.h":
        return (
            "Fortran fixed-form include for MPE logging: PARAMETER return codes MPE_LOG_* and external integer "
            "declarations for MPE logging routines (Init_log through Finish_log)."
        )
    if bn == "mpe_misc.h":
        return (
            "MPE miscellaneous C header: sequential-section helpers, tag management, I/O redirect, hostname, "
            "debugger launchers, 1D decomp, global rank; stub MPE_GetHostName when MPE_NOMPI."
        )
    if bn == "mpi.h":
        return (
            f"MPICH2 public C MPI header bundled under XBeach lib/x64/mpich ({n} lines). Defines MPI types, "
            f"error codes, communicators, datatypes, and prototypes for MPI-1/2 APIs; includes mpio.h for MPI-IO. "
            f"Enumerated {len([e for e in entities if e.startswith('function')])} function prototypes and "
            f"{len(constants)} #define constants."
        )
    if bn == "mpicxx.h":
        return (
            f"MPICH2 auto-generated C++ binding header (namespace MPI) with classes Comm, Intracomm, Intercomm, "
            f"Status, Request, Group, Op, Datatype, Info, Win, File and related methods; {n} lines, "
            f"{len([e for e in entities if 'class' in e])} class declarations."
        )
    if bn == "mpif.h":
        return (
            f"MPICH2 Fortran include (machine-generated by buildiface): PARAMETER/integer constants for MPI "
            f"error codes, datatypes, communicators, and related MPI Fortran bindings. {n} lines."
        )
    if bn == "mpio.h":
        return (
            f"ROMIO MPI-IO public C header: MPI_File/MPI_Offset types, file-mode and seek constants, "
            f"MPI-IO function prototypes (open/read/write/set_view/etc.). {n} lines."
        )
    if bn == "pyconfig.h":
        return (
            f"CPython Windows build configuration header (NOT auto-generated by configure): platform macros, "
            f"size/feature HAVE_* and MS_WIN* defines for embedding Python. {n} lines, {len(constants)} #defines."
        )
    return f"C/C++ header/source {bn}, {n} lines; {len(entities)} entities, {len(constants)} constants enumerated."




def _collapse_continued(lines):
    """Join lines that look like continued C prototypes."""
    out = []
    buf = None
    buf_i = 0
    for i, line in enumerate(lines, 1):
        s = line.rstrip()
        if buf is not None:
            buf = buf + " " + s.strip()
            if ";" in s or "{" in s:
                out.append((buf_i, buf))
                buf = None
            continue
        st = s.strip()
        if (
            st
            and not st.startswith("#")
            and not st.startswith("*")
            and not st.startswith("//")
            and "(" in s
            and ")" not in s
            and not st.endswith("\\")
            and re.match(r"^\s*(?:extern\s+)?[A-Za-z_].*", s)
        ):
            buf = s
            buf_i = i
            continue
        out.append((i, s))
    if buf is not None:
        out.append((buf_i, buf))
    return out


def extract_c_header(lines, path):
    entities = []
    constants = []
    calls = []
    io = []
    verbatim = []
    unresolved = []
    params_defined = []
    equations = []
    seen = set()

    re_def = re.compile(r"^\s*#\s*define\s+(\w+)(?:\s+(.*))?$")
    re_include = re.compile(r'^\s*#\s*include\s+[<\"]([^>\"]+)[>\"]')
    re_namespace = re.compile(r"^\s*namespace\s+(\w+)")
    re_class = re.compile(r"^\s*class\s+(\w+)")
    re_struct = re.compile(r"^\s*(?:typedef\s+)?struct\s+(\w+)")
    re_enum = re.compile(r"^\s*(?:typedef\s+)?enum\s+(\w+)")
    re_typedef = re.compile(r"^\s*typedef\s+.+\s+(\w+)\s*;")
    re_method = re.compile(
        r"^\s+(?:virtual\s+)?(?:static\s+)?(?:inline\s+)?"
        r"(?:const\s+)?[\w:<>\*&]+\s+(\w+)\s*\([^;]*\)\s*(?:const)?\s*;"
    )

    joined = _collapse_continued(lines)
    for i, line in joined:
        m = re_def.match(line)
        if m:
            name, val = m.group(1), (m.group(2) or "").strip()
            constants.append({"name": name, "value": val[:200], "line": i})
            key = f"#define {name}"
            if key not in seen:
                entities.append(f"#define {name} (L{i})")
                seen.add(key)
            continue
        m = re_include.match(line)
        if m:
            io.append(f"#include {m.group(1)} (L{i})")
            continue
        m = re_namespace.match(line)
        if m:
            key = f"namespace {m.group(1)}"
            if key not in seen:
                entities.append(f"namespace {m.group(1)} (L{i})")
                seen.add(key)
            continue
        m = re_class.match(line)
        if m:
            key = f"class {m.group(1)}"
            if key not in seen:
                entities.append(f"class {m.group(1)} (L{i})")
                seen.add(key)
            continue
        m = re_struct.match(line)
        if m and m.group(1):
            key = f"struct {m.group(1)}"
            if key not in seen:
                entities.append(f"struct {m.group(1)} (L{i})")
                seen.add(key)
            continue
        m = re_enum.match(line)
        if m and m.group(1):
            key = f"enum {m.group(1)}"
            if key not in seen:
                entities.append(f"enum {m.group(1)} (L{i})")
                seen.add(key)
            continue
        m = re_typedef.match(line)
        if m:
            key = f"typedef {m.group(1)}"
            if key not in seen:
                entities.append(f"typedef {m.group(1)} (L{i})")
                seen.add(key)
            continue
        m = re_method.match(line)
        if m:
            name = m.group(1)
            key = f"fn {name}"
            if key not in seen:
                entities.append(f"method {name} (L{i})")
                seen.add(key)
            continue
        if "(" in line and not line.strip().startswith("#") and not line.strip().startswith("*"):
            core = line.split("//")[0]
            if re.search(r"\)\s*;", core) or re.search(r"\)\s*\{", core) or re.search(r"\)\s*const\s*;", core):
                m2 = re.search(r"([A-Za-z_]\w*)\s*\([^;{]*\)\s*(?:const)?\s*[;{]", core)
                if not m2:
                    m2 = re.search(r"([A-Za-z_]\w*)\s*\(", core)
                if m2:
                    name = m2.group(1)
                    if name not in ("if", "for", "while", "switch", "return", "sizeof", "defined", "catch"):
                        key = f"fn {name}"
                        if key not in seen:
                            entities.append(f"function {name} (L{i})")
                            seen.add(key)

    # also scan original lines for class/method without collapse
    re_cxx_method = re.compile(
        r"^\s+(?:virtual\s+)?(?:static\s+)?(?:inline\s+)?"
        r"(?:explicit\s+)?"
        r"(?:const\s+)?(?:unsigned\s+|signed\s+)?"
        r"(?:[\w:<>\*&\s]+?\s+)"
        r"([A-Za-z_]\w*)\s*\("
    )
    re_ctor = re.compile(r"^\s+(?:explicit\s+)?(~?[A-Za-z_]\w*)\s*\(")
    for i, line in enumerate(lines, 1):
        m = re_class.match(line)
        if m:
            key = f"class {m.group(1)}"
            if key not in seen:
                entities.append(f"class {m.group(1)} (L{i})")
                seen.add(key)
        m = re_method.match(line)
        if m:
            name = m.group(1)
            key = f"fn {name}"
            if key not in seen:
                entities.append(f"method {name} (L{i})")
                seen.add(key)
            continue
        # C++ methods with body: "virtual void Barrier( void ) const" (no trailing ;)
        st = line.strip()
        if st.startswith(("if", "for", "while", "switch", "return", "case", "else", "typedef", "using", "friend", "enum", "struct", "class", "namespace", "public:", "private:", "protected:", "#", "//", "*", "{", "}")):
            continue
        if "(" not in line:
            continue
        m = re_cxx_method.match(line)
        if m:
            name = m.group(1)
            if name not in ("if", "for", "while", "switch", "return", "sizeof", "MPI_CHECK", "MPIX_CALL", "MPIX_CALLREF"):
                key = f"fn {name}"
                if key not in seen:
                    entities.append(f"method {name} (L{i})")
                    seen.add(key)
            continue
        # constructors / destructors: ClassName( or ~ClassName(
        m = re_ctor.match(line)
        if m and m.group(1)[0].isupper() or (m and m.group(1).startswith("~")):
            name = m.group(1)
            key = f"fn {name}"
            if key not in seen:
                entities.append(f"ctor {name} (L{i})")
                seen.add(key)

    what = describe_c(path, lines, entities, constants)
    for i, line in enumerate(lines, 1):
        if any(k in line for k in ("COPYRIGHT", "MPICH", "ROMIO", "Version", "buildiface")):
            verbatim.append({"text": line.strip()[:200], "loc": i})
            if len(verbatim) >= 4:
                break
    if not verbatim and lines:
        verbatim.append({"text": lines[0].strip()[:200], "loc": 1})

    return dict(
        what_it_is=what,
        entities=entities,
        constants=constants,
        params_defined=params_defined,
        equations=equations,
        io=io[:80],
        calls=calls,
        verbatim_spans=verbatim,
        unresolved=unresolved,
    )


def extract_fortran_include(lines, path):
    entities = []
    constants = []
    verbatim = []
    io = []
    seen = set()
    for i, line in enumerate(lines, 1):
        s = line.strip()
        for m in re.finditer(r"PARAMETER\s*\((.+)\)", line, re.I):
            body = m.group(1)
            for mm in re.finditer(r"(\w+)\s*=\s*([^,]+)", body):
                name, val = mm.group(1), mm.group(2).strip()
                constants.append({"name": name, "value": val, "line": i})
                key = f"param {name}"
                if key not in seen:
                    entities.append(f"parameter {name} (L{i})")
                    seen.add(key)
        m = re.match(r"(?:integer\s+)?external\s+(\w+)", s, re.I)
        if m:
            key = f"ext {m.group(1)}"
            if key not in seen:
                entities.append(f"external {m.group(1)} (L{i})")
                seen.add(key)
        m = re.match(r"integer\s+(\w+)", s, re.I)
        if m:
            name = m.group(1)
            key = f"int {name}"
            if key not in seen and f"param {name}" not in seen:
                entities.append(f"integer {name} (L{i})")
                seen.add(key)
        if re.search(r"\bcommon\b", s, re.I):
            entities.append(f"common (L{i}): {s[:100]}")
        if re.search(r"\bsave\b", s, re.I):
            entities.append(f"save (L{i}): {s[:100]}")
        if s.startswith("!") and any(k in s for k in ("Mode:", "Argonne", "DO NOT EDIT", "buildiface")):
            verbatim.append({"text": s[:200], "loc": i})

    bn = __import__("os").path.basename(path)
    if bn == "mpe_logf.h":
        what = (
            "Fortran include for MPE logging API: PARAMETER return codes and external integer symbols for "
            "MPE_Init_log through MPE_Finish_log."
        )
    elif bn == "mpif.h":
        what = (
            f"MPICH2 Fortran MPI include (machine-generated): PARAMETER constants and INTEGER/COMMON/SAVE "
            f"bindings. {len(lines)} lines; {len(constants)} PARAMETER entries; {len(entities)} entities."
        )
    else:
        what = f"Fortran include {bn}, {len(lines)} lines."

    if not verbatim and lines:
        verbatim.append({"text": lines[0].strip()[:200], "loc": 1})
    return dict(
        what_it_is=what,
        entities=entities,
        constants=constants,
        params_defined=[],
        equations=[],
        io=io,
        calls=[],
        verbatim_spans=verbatim[:5],
        unresolved=[],
    )

def extract_m4(lines: list[str], path: str) -> dict:
    entities = []
    constants = []
    calls = []
    io = []
    verbatim = []
    # AC_DEFUN([NAME], m4_define([NAME], m4_defun([NAME], AU_DEFUN([NAME], LT_OPTION_DEFINE
    re_def = re.compile(
        r"(?:AC_DEFUN|AU_DEFUN|m4_define|m4_defun)\s*\(\s*\[([^\]]+)\]"
    )
    re_def2 = re.compile(
        r"(?:AC_DEFUN|AU_DEFUN|m4_define|m4_defun)\s*\(\s*([A-Za-z0-9_]+)\s*,"
    )
    re_ltopt = re.compile(r"LT_OPTION_DEFINE\s*\(\s*\[([^\]]+)\]\s*,\s*\[([^\]]+)\]")
    seen_m = set()
    for i, line in enumerate(lines, 1):
        s = line.lstrip()
        m2 = re_ltopt.search(s)
        if m2:
            name = f"LT_OPTION_DEFINE {m2.group(1)}/{m2.group(2)}"
            if name not in seen_m:
                entities.append(f"{name} (L{i})")
                seen_m.add(name)
        for m in re_def.finditer(s):
            name = m.group(1)
            # skip LT_OPTION second-level false positives already handled
            key = name
            if key not in seen_m:
                entities.append(f"macro {name} (L{i})")
                seen_m.add(key)
        for m in re_def2.finditer(s):
            name = m.group(1)
            if name not in seen_m:
                entities.append(f"macro {name} (L{i})")
                seen_m.add(name)
        # m4_define([LT_PACKAGE_VERSION], [2.4.6])
        m = re.match(r"m4_define\(\[([^\]]+)\],\s*\[([^\]]*)\]\)", s)
        if m and m.group(1) in ("LT_PACKAGE_VERSION", "LT_PACKAGE_REVISION", "macro_version", "macro_revision"):
            constants.append({"name": m.group(1), "value": m.group(2), "line": i})
        if "serial " in s.lower() and s.startswith("#"):
            verbatim.append({"text": s[:200], "loc": i})
        if s.startswith("AC_SUBST") or s.startswith("AC_DEFINE"):
            calls.append(f"{s[:120]} (L{i})")
        if "AC_ARG_WITH" in s or "AC_ARG_ENABLE" in s:
            io.append(f"{s[:140]} (L{i})")

    bn = os.path.basename(path)
    descriptions = {
        "acx_mpi.m4": (
            "Autoconf macro ACX_MPI (Steven G. Johnson / Julian Cummings, v2006-10-13, GPLWithACException): "
            "probes MPI compilers (MPICC/MPICXX/MPIF77/MPIFC), link-tests MPI_Init, verifies mpi.h/mpif.h, "
            "AC_SUBSTs MPILIBS, defines HAVE_MPI."
        ),
        "acx_netcdf.m4": (
            "Local Autoconf macro ACX_NETCDF: --with-netcdf=DIR, Fortran link-tests nf90_close via use netcdf, "
            "AC_SUBSTs FCFLAGS_NETCDF/LIBS_NETCDF, defines HAVE_NETCDF."
        ),
        "fortran.m4": (
            "Fortran Autoconf helpers (Octopus lineage): ACX_LONG_FORTRAN_LINES, ACX_F90_ACCEPTS_LINE_NUMBERS, "
            "ACX_FORTRAN_CHECK_FUNC, AC_LANG_FUNC_LINK_TRY(Fortran), AC_LANG_PREPROC(Fortran), "
            "ACX_FORTRAN_LOC, ACX_FORTRAN_ISNAN, ACX_FORTRAN_IEEE_ARITHMETIC."
        ),
        "fortranextra.m4": (
            "Extra Fortran Autoconf macros: AC_FC_LINE_LENGTH, AC_FC_PREPROCESS, AC_F77_LINE_LENGTH, "
            "AX_FC_HAS_MODULE — probe long-line flags, preprocess flags, and module availability."
        ),
        "libtool.m4": (
            f"GNU Libtool core Autoconf macros (libtool.m4, {len(lines)} lines): LT_INIT and language/config "
            f"probes for shared library builds across hosts; {len(entities)} macro definitions enumerated."
        ),
        "ltoptions.m4": (
            "Libtool option-handling m4: LTOPTIONS_VERSION, _LT_SET_OPTION/_LT_IF_OPTION/_LT_SET_OPTIONS, "
            "LT_OPTION_DEFINE handlers for dlopen/win32-dll/shared/static/fast-install/pic/aix-soname and LTDL_INIT modes."
        ),
        "ltsugar.m4": (
            "Libtool m4 sugar layer: LTSUGAR_VERSION, lt_join/lt_car/lt_cdr/lt_append/lt_combine/"
            "lt_if_append_uniq/lt_dict_* helpers for Autoconf 2.59 compatibility."
        ),
        "ltversion.m4": (
            "Libtool version stamp: m4_define LT_PACKAGE_VERSION/REVISION 2.4.6; AC_DEFUN LTVERSION_VERSION."
        ),
        "lt~obsolete.m4": (
            "Libtool aclocal bootstrap shim: AC_DEFUN stubs for withdrawn macro names so aclocal does not "
            "pull old system libtool.m4; LTOBSOLETE_VERSION plus ~60 empty AC_DEFUN placeholders."
        ),
        "pkg.m4": (
            "pkg-config Autoconf macros (pkg-config-0.24 serial 1): PKG_PROG_PKG_CONFIG, PKG_CHECK_EXISTS, "
            "_PKG_CONFIG, _PKG_SHORT_ERRORS_SUPPORTED, PKG_CHECK_MODULES."
        ),
    }
    what = descriptions.get(bn, f"Autoconf m4 file {bn}, {len(lines)} lines, {len(entities)} macro defs.")
    if not verbatim and lines:
        for i, line in enumerate(lines[:30], 1):
            if line.strip().startswith("#") and "Copyright" in line:
                verbatim.append({"text": line.strip()[:200], "loc": i})
                break
        if not verbatim:
            verbatim.append({"text": lines[0].strip()[:200], "loc": 1})
    return dict(
        what_it_is=what,
        entities=entities,
        constants=constants,
        params_defined=[],
        equations=[],
        io=io[:40],
        calls=calls[:40],
        verbatim_spans=verbatim[:5],
        unresolved=[],
    )


def extract_python(lines: list[str], path: str) -> dict:
    entities = []
    constants = []
    calls = []
    io = []
    verbatim = []
    params_defined = []
    re_class = re.compile(r"^class\s+(\w+)")
    re_def = re.compile(r"^(\s*)def\s+(\w+)\s*\(")
    re_async = re.compile(r"^(\s*)async\s+def\s+(\w+)\s*\(")
    for i, line in enumerate(lines, 1):
        m = re_class.match(line)
        if m:
            entities.append(f"class {m.group(1)} (L{i})")
        m = re_def.match(line) or re_async.match(line)
        if m:
            indent, name = m.group(1), m.group(2)
            kind = "method" if indent else "function"
            entities.append(f"{kind} {name} (L{i})")
        # module-level setup(...) is the only entry in distutils scripts
        if re.match(r"^setup\s*\(", line):
            entities.append(f"call setup (L{i})")
        # module-level assignment of simple constants
        m = re.match(r"^([A-Z][A-Z0-9_]*)\s*=\s*(.+)$", line)
        if m:
            constants.append({"name": m.group(1), "value": m.group(2).strip()[:120], "line": i})
        m = re.match(r"^([a-z_][a-z0-9_]*)\s*=\s*([0-9]+|['\"].*['\"]|True|False|None)\s*$", line)
        if m and m.group(1) in ("version", "dllsuffix") or (
            m and not m.group(1).startswith("_") and m.group(1) in ("WD",)
        ):
            constants.append({"name": m.group(1), "value": m.group(2).strip()[:120], "line": i})
        if re.match(r"^(import |from )", line):
            calls.append(f"{line.strip()} (L{i})")
        if "open(" in line or "with open" in line:
            io.append(f"{line.strip()[:140]} (L{i})")

    bn = os.path.basename(path)
    if bn == "makedepo.py":
        what = (
            "Python Fortran dependency scanner: parses module/use/include lines from source args; "
            "outputs make rules in modes O:FHO/O:FH/O:M/M:F via -m/-p/-s options."
        )
    elif bn == "generate.py":
        what = (
            "XBeach Fortran source generator: parses variables.def/params.def with regex, maps Fortran types, "
            "renders mako templates under xbeachlibrary/templates to .inc files; requires mako package."
        )
    elif bn == "libxbeach.py":
        what = (
            "Python ctypes proxy class XBeach for libxbeach shared library: init/executestep/output, "
            "parameter get/set, array get/set by rank/type, finalize with dlclose; platform dllsuffix map."
        )
    elif bn == "test_libxbeach.py":
        what = (
            "unittest suite TestXBeach and IntegrationTest for libxbeach.XBeach proxy against example1 data; "
            "tests parameter/array APIs, executestep, and rewind consistency."
        )
    elif bn == "setup.py" and "scripts" in path:
        what = "distutils/py2exe setup for packaging scripts/generate.py as console exe with pygments.styles.default include."
    elif bn == "setup.py":
        what = (
            "setuptools setup for pybeach package 'XBeach' v0.1 (Fedor Baart): numpy/matplotlib/nose deps, GPLv3."
        )
    elif bn == "__init__.py":
        what = f"Empty Python package marker ({path})."
    else:
        what = f"Python file {bn}, {len(lines)} lines, {len(entities)} defs/classes."

    for i, line in enumerate(lines, 1):
        if '"""' in line or "'''" in line:
            verbatim.append({"text": line.strip()[:200], "loc": i})
            if len(verbatim) >= 2:
                break
    if not verbatim and lines:
        verbatim.append({"text": (lines[0] if lines else "")[:200], "loc": 1 if lines else 0})

    return dict(
        what_it_is=what,
        entities=entities,
        constants=constants,
        params_defined=params_defined,
        equations=[],
        io=io,
        calls=calls[:40],
        verbatim_spans=verbatim[:5],
        unresolved=[],
    )


def extract_fortran_src(lines: list[str], path: str) -> dict:
    entities = []
    constants = []
    calls = []
    io = []
    verbatim = []
    re_mod = re.compile(r"^\s*module\s+(\w+)", re.I)
    re_prog = re.compile(r"^\s*program\s+(\w+)", re.I)
    re_sub = re.compile(r"^\s*(?:recursive\s+)?(?:pure\s+)?(?:elemental\s+)?subroutine\s+(\w+)", re.I)
    re_fn = re.compile(
        r"^\s*(?:(?:integer|real|logical|character|double\s+precision|type)(?:\([^)]*\))?\s+)?"
        r"(?:recursive\s+)?(?:pure\s+)?function\s+(\w+)",
        re.I,
    )
    re_fn2 = re.compile(
        r"^\s*([\w()*=]+)\s+function\s+(\w+)", re.I
    )
    re_use = re.compile(r"^\s*use\s+(\w+)", re.I)
    re_call = re.compile(r"^\s*call\s+(\w+)", re.I)
    for i, line in enumerate(lines, 1):
        s = line.split("!")[0]
        m = re_mod.match(s)
        if m:
            entities.append(f"module {m.group(1)} (L{i})")
        m = re_prog.match(s)
        if m:
            entities.append(f"program {m.group(1)} (L{i})")
        m = re_sub.match(s)
        if m:
            entities.append(f"subroutine {m.group(1)} (L{i})")
        m = re_fn.match(s)
        if m:
            entities.append(f"function {m.group(1)} (L{i})")
        else:
            m = re_fn2.match(s)
            if m and m.group(2).lower() not in ("end",):
                entities.append(f"function {m.group(2)} (L{i})")
        m = re_use.match(s)
        if m:
            calls.append(f"use {m.group(1)} (L{i})")
        m = re_call.match(s)
        if m:
            calls.append(f"call {m.group(1)} (L{i})")
        if "write(" in s.lower() or "read(" in s.lower() or "print" in s.lower():
            io.append(f"{s.strip()[:120]} (L{i})")
        if "Welcome to XBeach" in line or "XBeach version" in line:
            verbatim.append({"text": line.strip()[:200], "loc": i})

    bn = os.path.basename(path)
    if bn == "input.F90":
        what = (
            "Fortran module process_input: function readinput() parses CLI (-V version banner, -h/--help usage) "
            "via command_argument_count/get_command_argument; returns c_int 1 to signal early exit."
        )
    elif bn == "xbeach.F90":
        what = (
            "Main program xbeach: readinput → init → time loop (executestep/outputext while t<tstop via "
            "getdoubleparameter) → final; uses libxbeach_module, introspection_module, process_input, xmpi_module."
        )
    else:
        what = f"Fortran source {bn}, {len(lines)} lines."

    if not verbatim and lines:
        verbatim.append({"text": lines[0].strip()[:200], "loc": 1})
    return dict(
        what_it_is=what,
        entities=entities,
        constants=constants,
        params_defined=[],
        equations=[],
        io=io,
        calls=calls,
        verbatim_spans=verbatim[:5],
        unresolved=[],
    )


def extract_makefile(lines: list[str], path: str) -> dict:
    entities = []
    constants = []
    calls = []
    io = []
    verbatim = []
    for i, line in enumerate(lines, 1):
        s = line.strip()
        if not s or s.startswith("#"):
            if s.startswith("#") and len(verbatim) < 2:
                verbatim.append({"text": s[:200], "loc": i})
            continue
        m = re.match(r"^([A-Za-z_][\w]*)\s*([:+]?=)\s*(.*)$", line)
        if m and not line.startswith("\t"):
            name, op, val = m.group(1), m.group(2), m.group(3).strip()
            constants.append({"name": name, "value": val[:200], "line": i})
            entities.append(f"var {name} (L{i})")
        m = re.match(r"^([A-Za-z_][\w%-]*)\s*:", line)
        if m and not line.startswith("\t"):
            entities.append(f"target {m.group(1)} (L{i})")
        if s.startswith("include ") or s.startswith("$(MAKE)") or s.startswith("$(MAKEDEPO)"):
            calls.append(f"{s[:120]} (L{i})")
        if "SUBDIRS" in s or "bin_PROGRAMS" in s or "SOURCES" in s:
            io.append(f"{s[:140]} (L{i})")

    bn = path
    if bn.endswith("src/Makefile.am"):
        what = "Automake for src/: SUBDIRS=xbeachlibrary xbeach; dep/depclean recurse into both."
    elif bn.endswith("xbeach/Makefile.am"):
        what = (
            "Automake for bin xbeach: sources input.F90 xbeach.F90, links libxbeach.la; "
            "USEMPI/USENETCDF conditionals; depclean/dep via MAKEDEPO."
        )
    else:
        what = f"Makefile/Automake {os.path.basename(path)}, {len(lines)} lines."
    if not verbatim and lines:
        verbatim.append({"text": lines[0].strip()[:200], "loc": 1})
    return dict(
        what_it_is=what,
        entities=entities,
        constants=constants,
        params_defined=[],
        equations=[],
        io=io,
        calls=calls,
        verbatim_spans=verbatim[:5],
        unresolved=[],
    )


def extract_shell(lines: list[str], path: str) -> dict:
    entities = []
    constants = []
    calls = []
    io = []
    verbatim = []
    for i, line in enumerate(lines, 1):
        s = line.strip()
        if s.startswith("#") and len(verbatim) < 3:
            verbatim.append({"text": s[:200], "loc": i})
        m = re.match(r"^(?:export\s+)?([A-Za-z_][\w]*)=(.*)$", s)
        if m and not s.startswith("rem ") and not s.lower().startswith("set "):
            constants.append({"name": m.group(1), "value": m.group(2).strip()[:120], "line": i})
        # bat set VAR=
        m = re.match(r"set\s+([A-Za-z_][\w]*)=(.*)$", s, re.I)
        if m:
            constants.append({"name": m.group(1), "value": m.group(2).strip()[:120], "line": i})
            entities.append(f"var {m.group(1)} (L{i})")
        for cmd in ("rm", "rmdir", "mkdir", "copy", "xcopy", "del", "find", "grep", "7za", "cd"):
            if re.search(rf"\b{cmd}\b", s, re.I):
                calls.append(f"{s[:120]} (L{i})")
                break
        if "rm -f" in s or "copy " in s.lower() or "mkdir " in s.lower():
            io.append(f"{s[:140]} (L{i})")

    bn = os.path.basename(path)
    if bn == "mpi_filter":
        what = "Bash one-liner filter: grep -v 'warning:.*mpi_' then exit 0; strips MPI-related compiler warnings."
        entities.append("script mpi_filter (L1)")
    elif bn == "rmdiv":
        what = (
            "Bash cleanup: removes autoconf-generated Makefile.in, configure, libtool, aclocal.m4, "
            "config/*, and m4 libtool suite files."
        )
        entities.append("script rmdiv (L1)")
    elif bn == "distribute.bat":
        what = (
            "Windows bat: clears dist/<Platform>/<Config>, copies static dlls into TargetDir, "
            "copies exe/dll into dist, copies manual PDF and LICENSE."
        )
    elif bn == "zip.bat":
        what = (
            "Windows bat: copies 7za.exe into dist folder, creates xbeach_<Config>_<Platform>.zip of all files, "
            "removes 7za.exe from archive and disk."
        )
    else:
        what = f"Shell/batch script {bn}, {len(lines)} lines."
    if not verbatim and lines:
        verbatim.append({"text": lines[0].strip()[:200], "loc": 1})
    return dict(
        what_it_is=what,
        entities=entities,
        constants=constants,
        params_defined=[],
        equations=[],
        io=io,
        calls=calls,
        verbatim_spans=verbatim[:5],
        unresolved=[],
    )


def extract_text(lines: list[str], path: str) -> dict:
    entities = []
    constants = []
    io = []
    verbatim = []
    bn = os.path.basename(path)
    if bn == "DEPENDENCIES.txt":
        what = (
            "py2exe dependency notice listing system DLLs (OLEAUT32, USER32, SHELL32, ole32, ADVAPI32, "
            "WS2_32, GDI32, VERSION, KERNEL32) not bundled with the executable."
        )
        for i, line in enumerate(lines, 1):
            m = re.search(r"(\w+\.dll)\s*-\s*(.+)", line, re.I)
            if m:
                entities.append(f"dll {m.group(1)} (L{i})")
                constants.append({"name": m.group(1), "value": m.group(2).strip(), "line": i})
    elif bn == "info.txt":
        what = (
            "Notes on building generate.py executable: (1) py2exe+setup.py failed 5-9-2019; "
            "(2) use pyinstaller generate.py → dist/generate/*."
        )
        entities.append("doc info.txt")
    elif bn == "setup.cfg":
        what = "setuptools egg_info config: tag_build=dev, tag_svn_revision=true."
        for i, line in enumerate(lines, 1):
            m = re.match(r"(\w+)\s*=\s*(.*)", line)
            if m:
                constants.append({"name": m.group(1), "value": m.group(2).strip(), "line": i})
                entities.append(f"key {m.group(1)} (L{i})")
        if lines and lines[0].startswith("["):
            entities.insert(0, f"section {lines[0].strip()} (L1)")
    else:
        what = f"Text file {bn}, {len(lines)} lines."
        entities.append(f"file {bn}")
    if lines:
        verbatim.append({"text": lines[0].strip()[:200], "loc": 1})
        if len(lines) > 1:
            verbatim.append({"text": lines[-1].strip()[:200], "loc": len(lines)})
    return dict(
        what_it_is=what,
        entities=entities,
        constants=constants,
        params_defined=[],
        equations=[],
        io=io,
        calls=[],
        verbatim_spans=verbatim,
        unresolved=[],
    )


def extract_xml(lines: list[str], path: str) -> dict:
    entities = []
    constants = []
    io = []
    verbatim = []
    text = "\n".join(lines)
    bn = os.path.basename(path)
    # tags
    for i, line in enumerate(lines, 1):
        for m in re.finditer(r"<(\w+)([^>]*)>", line):
            tag, attrs = m.group(1), m.group(2)
            if tag.startswith("?"):
                continue
            if tag in ("VisualStudioProject", "Platform", "Configuration", "Tool", "File",
                       "assembly", "assemblyIdentity", "dependentAssembly", "supportedOS",
                       "dependency", "compatibility", "application"):
                name_m = re.search(r'Name="([^"]+)"', attrs)
                id_m = re.search(r'Id="([^"]+)"', attrs)
                n_m = re.search(r'name="([^"]+)"', attrs)
                label = name_m.group(1) if name_m else (n_m.group(1) if n_m else (id_m.group(1) if id_m else tag))
                entities.append(f"xml {tag}:{label} (L{i})")
            if "Include=" in attrs:
                im = re.search(r'Include="([^"]+)"', attrs)
                if im:
                    io.append(f"Include {im.group(1)} (L{i})")
            for km in re.finditer(r'(\w+)="([^"]*)"', attrs):
                if km.group(1) in ("Version", "ProjectIdGuid", "Keyword", "ProjectCreator",
                                   "processorArchitecture", "publicKeyToken", "type", "version",
                                   "manifestVersion"):
                    constants.append({"name": f"{tag}.{km.group(1)}", "value": km.group(2)[:120], "line": i})

    if bn.endswith(".manifest"):
        what = (
            "Windows side-by-side assembly manifest for generate.exe: amd64 win32 identity, depends on "
            "Microsoft.Windows.Common-Controls v6, lists supportedOS GUIDs (Vista through Windows 10)."
        )
    elif bn.endswith(".vfproj"):
        what = (
            f"Intel Fortran Visual Studio project for xbeach Console Application v11.0; platforms Win32/x64; "
            f"{len(lines)} lines of configurations/tools/files."
        )
    else:
        what = f"XML file {bn}, {len(lines)} lines."
    if lines:
        verbatim.append({"text": lines[0].strip()[:200], "loc": 1})
    # dedupe entities somewhat
    seen = set()
    ent2 = []
    for e in entities:
        if e not in seen:
            seen.add(e)
            ent2.append(e)
    return dict(
        what_it_is=what,
        entities=ent2,
        constants=constants,
        params_defined=[],
        equations=[],
        io=io[:50],
        calls=[],
        verbatim_spans=verbatim[:5],
        unresolved=[],
    )


def extract_fortran_f_style_header(lines: list[str], path: str) -> dict:
    """mpe_logf.h and mpif.h style."""
    return extract_fortran_include(lines, path)


def process_file(rel: str) -> dict:
    p = BASE / rel
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    if not p.exists():
        return {
            "axis": AXIS,
            "model": MODEL,
            "path": rel,
            "sha256": "",
            "bytes": 0,
            "lines_or_pages": 0,
            "read_status": "failed",
            "read_range": "",
            "reader": READER,
            "read_at": now,
            "content": {
                "what_it_is": "file missing",
                "entities": [],
                "constants": [],
                "params_defined": [],
                "equations": [],
                "io": [],
                "calls": [],
                "verbatim_spans": [],
                "unresolved": [f"path not found under {BASE}"],
            },
        }

    digest = sha256_file(p)
    nbytes = p.stat().st_size
    nlines = wc_l(p)
    text, lines, status = read_text(p)
    if status == "failed":
        return {
            "axis": AXIS,
            "model": MODEL,
            "path": rel,
            "sha256": digest,
            "bytes": nbytes,
            "lines_or_pages": nlines,
            "read_status": "failed",
            "read_range": "",
            "reader": READER,
            "read_at": now,
            "content": {
                "what_it_is": "binary or undecodable",
                "entities": [],
                "constants": [],
                "params_defined": [],
                "equations": [],
                "io": [],
                "calls": [],
                "verbatim_spans": [],
                "unresolved": ["decode failed"],
            },
        }

    # Ensure we have full line list matching content for enumeration
    # Re-split carefully: use text.splitlines() which may undercount final empty
    # but we already have nlines from wc

    bn = os.path.basename(rel)
    ext = Path(rel).suffix.lower()

    # route
    if bn in ("mpe_logf.h", "mpif.h") or (
        ext == ".h" and lines and (lines[0].lstrip().startswith("!") or "Mode: Fortran" in (lines[0] + (lines[1] if len(lines) > 1 else "")))
    ):
        content = extract_fortran_f_style_header(lines, rel)
    elif ext in (".h", ".hpp", ".c", ".cpp", ".cc", ".cxx"):
        content = extract_c_header(lines, rel)
    elif ext == ".m4" or "lt~obsolete" in bn:
        content = extract_m4(lines, rel)
    elif ext == ".py":
        content = extract_python(lines, rel)
    elif ext in (".f90", ".F90", ".f", ".F", ".for"):
        content = extract_fortran_src(lines, rel)
    elif bn in ("Makefile.am", "Makefile", "Makefile.in") or ext in (".am", ".mk"):
        content = extract_makefile(lines, rel)
    elif ext in (".bat", ".cmd", ".sh") or bn in ("mpi_filter", "rmdiv"):
        content = extract_shell(lines, rel)
    elif ext in (".xml", ".vfproj", ".manifest") or bn.endswith(".manifest"):
        content = extract_xml(lines, rel)
    elif ext in (".txt", ".cfg", ".md", ".rst") or bn.endswith(".cfg"):
        content = extract_text(lines, rel)
    else:
        # generic full read
        content = extract_text(lines, rel)
        content["what_it_is"] = f"Generic text file {bn}, {nlines} lines (full read)."

    # empty file special
    if nbytes == 0:
        content = {
            "what_it_is": f"Empty file {rel} (0 bytes).",
            "entities": [],
            "constants": [],
            "params_defined": [],
            "equations": [],
            "io": [],
            "calls": [],
            "verbatim_spans": [],
            "unresolved": [],
        }

    # assert full coverage: we loaded all lines into memory
    read_status = "complete"
    read_range = ""
    # sanity: if line count huge but we have them, still complete
    if len(lines) < nlines and nlines > 0 and nbytes > 0:
        # splitlines dropped trailing empty only — still complete content
        pass

    return {
        "axis": AXIS,
        "model": MODEL,
        "path": rel,
        "sha256": digest,
        "bytes": nbytes,
        "lines_or_pages": nlines,
        "read_status": read_status,
        "read_range": read_range,
        "reader": READER,
        "read_at": now,
        "content": content,
    }


def main():
    rels = [ln.strip() for ln in SHARD.read_text().splitlines() if ln.strip()]
    records = []
    for rel in rels:
        rec = process_file(rel)
        records.append(rec)
        print(f"{rec['read_status']:8} {rec['lines_or_pages']:6} {len(rec['content']['entities']):5} ents  {rel}", file=sys.stderr)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False, separators=(",", ":")) + "\n")
    print(f"{len(records)}/{len(rels)}", file=sys.stderr)
    print(f"{len(records)}/{len(rels)}")


if __name__ == "__main__":
    main()
