"""Freeze the reviewed source spans for build/mode and selected manual contracts."""
import hashlib,json,re
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[5];SRC=ROOT/'models/XBeach/raw/source_code/trunk'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ev(rel,a,b):
 p=SRC/rel;raw=p.read_bytes();assert 1 <= a <= b <= len(raw.split(b'\n'))-(1 if raw.endswith(b'\n') else 0),(rel,a,b);return {'path':str(p.relative_to(ROOT)),'line_start':a,'line_end':b,'sha256':sha(p),'quote_exact_utf8':b'\n'.join(raw.split(b'\n')[a-1:b]).decode()}
spans=[('src/xbeachlibrary/wave_timestep.F90',34,115),('src/xbeachlibrary/libxbeach.F90',283,310),('src/xbeachlibrary/flow_timestep.F90',630,658),('src/xbeachlibrary/nonh.F90',201,249),('src/xbeachlibrary/params.F90',1359,1369),('src/xbeachlibrary/params.F90',1559,1563),('src/xbeachlibrary/params.F90',1740,1758),('src/xbeachlibrary/params.F90',1884,1910),('src/xbeachlibrary/params.F90',1940,1954),('src/xbeachlibrary/params.F90',286,290),('scripts/generate.py',33,41),('scripts/generate.py',215,262),('src/xbeachlibrary/build/generate_and_copy_gen_files.bat',18,23),('src/xbeachlibrary/Makefile.am',62,113),('src/xbeachlibrary/solver.F90',9,25),('src/xbeachlibrary/solver.F90',205,214),('src/xbeachlibrary/wave_functions.F90',978,1019),('src/xbeachlibrary/wave_functions.F90',1020,1108),('src/xbeachlibrary/wave_functions.F90',1176,1211),('src/xbeachlibrary/morphevolution.F90',731,804),('src/xbeachlibrary/morphevolution.F90',640,644)]
modes=[
 {'id':'stationary','guard':'swave==1 and wavemodel==STATIONARY','sequence':['wave','wave_dispersion(0)','wave_stationary_directions(0)'],'update_guard':'abs(mod(t,wavint)) < 0.001*dt or newstatbc==1'},
 {'id':'surfbeat_directional','guard':'swave==1 and wavemodel==SURFBEAT and single_dir!=1','sequence':['wave','optional update_means_wave_flow if wci==1','wave_dispersion(2 if wci==1 else 0)','wave_instationary'],'update_guard':'each successful physics step'},
 {'id':'surfbeat_single_dir','guard':'swave==1 and wavemodel==SURFBEAT and single_dir==1','sequence':['wave','update_means_wave_flow','conditional wave_dispersion(1), wave_stationary_directions(1)','wave_dispersion(2 if wci==1 else 0)','wave_instationary'],'update_guard':'direction solve at abs(mod(t,wavint)) < 0.001*dt or newstatbc==1 or t==dt; wave_instationary each successful physics step'},
 {'id':'nonh_one_layer','guard':'wavemodel==NONH and nonhq3d!=1','sequence':['flow','nonh_cor(0) -> nonh_1lay_pred','flow_secondorder_advUV','nonh_cor(1) -> nonh_1lay_cor'],'update_guard':'each successful physics step; input validation turns secorder on'},
 {'id':'nonh_two_layer_2dv','guard':'wavemodel==NONH and nonhq3d==1 and s%ny==0','sequence':['flow','nonh_cor(0) -> nonh_2lay_pred_2dV','flow_secondorder_advUV','nonh_cor(1) -> nonh_2lay_cor_2dV'],'update_guard':'each successful physics step; local s%ny selects the branch'},
 {'id':'nonh_two_layer_3d','guard':'wavemodel==NONH and nonhq3d==1 and s%ny!=0','sequence':['flow','nonh_cor(0) -> nonh_2lay_pred_3d','flow_secondorder_advUV','nonh_cor(1) -> nonh_2lay_cor_3d'],'update_guard':'each successful physics step; local s%ny selects the branch'}]
callees={'wave_timestep.F90':['wave'],'wave_functions.F90':['wave_dispersion','update_means_wave_flow'],'wave_stationary_directions.F90':['wave_stationary_directions'],'wave_instationary.F90':['wave_instationary'],'flow_timestep.F90':['flow'],'flow_secondorder.F90':['flow_secondorder_advUV'],'nonh.F90':['nonh_cor','nonh_1lay_pred','nonh_1lay_cor','nonh_2lay_pred_2dv','nonh_2lay_cor_2dv','nonh_2lay_pred_3d','nonh_2lay_cor_3d']}
definitions=[]
for f,names in callees.items():
 p=SRC/'src/xbeachlibrary'/f
 for name in names:
  matches=[(i,l) for i,l in enumerate(p.read_bytes().split(b'\n'),1) if re.match(rb'\s*subroutine\s+'+name.encode()+rb'\s*\(',l,re.I)]
  assert len(matches)==1,(name,matches)
  definitions.append({'name':name,'source':ev('src/xbeachlibrary/'+f,matches[0][0],matches[0][0])})
contracts={'date':'2026-09-12','scope':'Top-level wave/nonhydrostatic dispatch and selected manual semantics; not every numerical option or complete routine reachability','human_approval_issued':False,'modes':modes,'definitions':definitions,'source_evidence':[ev(*s) for s in spans],'source_notes':['MPI is a compile configuration; swave/nonhq3d/single_dir are runtime controls and are not independent freely combinable options','The six dispatch paths do not enumerate sediment forms, boundary types or every numerical option','Stationary/single_dir automatic MPI partition forces MPIBOUNDARY_X for ny>0 subject to size check; manual partition is an explicit exception','No runtime exclusion of nonh follows from obsolete solver.F90 header comment; actual files and MPI branches remain compiled'],'manual_findings':[{'id':'XB-EQ-WCI','documents':'Kingsday/Master equations (2.5)-(2.10)','conclusion':'Superscript tilde denotes wave-number correction, explicitly defined in the following paragraph. Current kmx/kmy updates include a cross-derivative term, depth-weighted Doppler contribution, k<=25 and intrinsic-frequency/steepness adjustments; do not claim literal identity to the compact manual equations.','status':'document_role_resolved_implementation_differences_recorded'},{'id':'XB-EQ-BED','documents':'Kingsday B.37 / Master C.37','conclusion':'First line literally ends 0a; no separate a-dependent source exists in the corresponding sourcesink branches. Code computes positive erosion dzg with morfac*dt/(1-por) and subtracts it from zb. sourcesink=0 uses suspended+bed-load flux divergence; sourcesink=1 replaces suspended divergence with ero-depo_ex. ny==0 retains lsgrad terms.','status':'implementation_contract_resolved_authorial_a_intent_unspecified'}]}
prior=ROOT/'_staging/total-read/model-audit/XBeach/connectivity/manuals-docx-read/glyph-record-read/receipt.json';receipt=json.loads(prior.read_text());contracts['prior_glyph_receipt']={'path':str(prior.relative_to(ROOT)),'sha256':sha(prior)}
contracts['document_sources']=list({r['source']['path']:r['source'] for r in receipt['records']}.values())
contracts['visual_evidence']=[]
for version,page,eq in [('master',19,'2.5-2.10'),('kingsday',19,'2.5-2.10'),('master',138,'C.37'),('kingsday',135,'B.37')]:
 p=ROOT/f'_staging/total-read/model-audit/XBeach/connectivity/manuals-docx-read/full-visual-read/{version}/page-{page:03}.png'
 contracts['visual_evidence'].append({'path':str(p.relative_to(ROOT)),'sha256':sha(p),'restored_docx_physical_page':page,'equations':eq,'inspected':True})
(HERE/'contracts.json').write_text(json.dumps(contracts,ensure_ascii=False,indent=2)+'\n')
print('Recorded',len(modes),'dispatch paths,',len(definitions),'callee definitions and',len(spans),'source spans')
